# Generated by Django 5.2 on 2025-04-21 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_following'),
    ]

    operations = [
        migrations.RenameField(
            model_name='following',
            old_name='following',
            new_name='following_user',
        ),
    ]
