# Generated by Django 5.2 on 2025-04-16 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_media'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='media_url',
            new_name='media',
        ),
    ]
