# Generated by Django 5.2 on 2025-04-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_media_url_media_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='media',
        ),
        migrations.AddField(
            model_name='media',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='blog_media/'),
        ),
    ]
